// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNxZqeDGvs4oolqNFB_sVEMZRdjGaJxxE',
    appId: '1:762457578824:web:3a561e5acf4b45efb8277d',
    messagingSenderId: '762457578824',
    projectId: 'braderieppe',
    authDomain: 'braderieppe.firebaseapp.com',
    databaseURL: 'https://braderieppe-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'braderieppe.appspot.com',
    measurementId: 'G-YXWYSLLCL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIQZi8KJeAG3ew35FSehJy8_CnomibIx4',
    appId: '1:762457578824:android:61cdd14fd117a3d0b8277d',
    messagingSenderId: '762457578824',
    projectId: 'braderieppe',
    databaseURL: 'https://braderieppe-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'braderieppe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIQD1ryX_p96P-tB9me4olR5HBLXsba7Q',
    appId: '1:762457578824:ios:4627152f254de91cb8277d',
    messagingSenderId: '762457578824',
    projectId: 'braderieppe',
    databaseURL: 'https://braderieppe-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'braderieppe.appspot.com',
    iosClientId: '762457578824-dbjd9j73m12pfk4sq228lsfnujtei5i8.apps.googleusercontent.com',
    iosBundleId: 'com.example.braderiePpe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIQD1ryX_p96P-tB9me4olR5HBLXsba7Q',
    appId: '1:762457578824:ios:4627152f254de91cb8277d',
    messagingSenderId: '762457578824',
    projectId: 'braderieppe',
    databaseURL: 'https://braderieppe-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'braderieppe.appspot.com',
    iosClientId: '762457578824-dbjd9j73m12pfk4sq228lsfnujtei5i8.apps.googleusercontent.com',
    iosBundleId: 'com.example.braderiePpe',
  );
}
